import React, { useEffect, useRef, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Map from "ol/Map";
import View from "ol/View";
import OlLayerTile from "ol/layer/Tile";
import XYZ from "ol/source/XYZ";
const initLayers = [
    new OlLayerTile({
        source: new XYZ({
            url: "http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}",
        }),
    }),
    new OlLayerTile({
        source: new XYZ({
            url: "http://mt0.google.com/vt/lyrs=p&hl=en&x={x}&y={y}&z={z}",
        }),
    }),
];

const Home: NextPage = () => {
    const mapElement = useRef<HTMLDivElement | null>(null);
    const [map, setMap] = useState<Map | undefined>();

    useEffect(() => {
        setMap(initMap(mapElement));
    }, []);
    function initMap(mapElement: React.MutableRefObject<HTMLDivElement | null>): Map | undefined {
        if (!mapElement.current) return;

        const view = new View({
            projection: "EPSG:4326",
            center: [0, 0],
            zoom: 2,
        });

        const map = new Map({
            layers: initLayers,
            view: view,
            controls: [],
        });
        map.setTarget(mapElement.current);
        return map;
    }

    return <div id="Map-provider" ref={mapElement} className={styles.map} />;
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div id="Map-provider" ref={mapElement} style={{ width: "100%", height: "100%", padding: 0 }} />
            </main>
        </div>
    );
};

export default Home;
